// <auto-generated />
namespace AgentSignalBar.Windows.Properties;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("SettingsSingleFileGenerator", "1.0.0.0")]
internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
{
    private static readonly Settings defaultInstance = (Settings)global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings());

    public static Settings Default => defaultInstance;

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("Mica")]
    public string BackdropMode
    {
        get => (string)this[nameof(BackdropMode)];
        set => this[nameof(BackdropMode)] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    public bool ShowFloatingSignal
    {
        get => (bool)this[nameof(ShowFloatingSignal)];
        set => this[nameof(ShowFloatingSignal)] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("-1")]
    public int FloatingSignalX
    {
        get => (int)this[nameof(FloatingSignalX)];
        set => this[nameof(FloatingSignalX)] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("-1")]
    public int FloatingSignalY
    {
        get => (int)this[nameof(FloatingSignalY)];
        set => this[nameof(FloatingSignalY)] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("TopRight")]
    public string FloatingSignalPosition
    {
        get => (string)this[nameof(FloatingSignalPosition)];
        set => this[nameof(FloatingSignalPosition)] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("False")]
    public bool IsPositionLocked
    {
        get => (bool)this[nameof(IsPositionLocked)];
        set => this[nameof(IsPositionLocked)] = value;
    }

    [global::System.Configuration.UserScopedSettingAttribute()]
    [global::System.Configuration.DefaultSettingValueAttribute("True")]
    public bool TrackWorkBuddy
    {
        get => (bool)this[nameof(TrackWorkBuddy)];
        set => this[nameof(TrackWorkBuddy)] = value;
    }
}
